---
micronaut:
    application:
        name: rabbitmq
---
rabbitmq:
    uri: amqp://localhost:5672
    # For some reason it is also necessary to define the port when running in Gitlab CI
    port: 5672
